version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max_old_space_size=4096"
    LAMBDA_FUNCTION_NAME: "event-link"
    S3_BUCKET: "event-link-lamba"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g npm@10

  build:
    commands:
      - echo "Installing dependencies"
      - npm ci
      - echo "Cleaning previous build artifacts"
      - rm -rf dist function.zip
      - echo "Building Lambda bundle with esbuild"
      - npm run build
      - echo "Packaging bundled output"
      - zip -r function.zip dist appspec.yml

  post_build:
    commands:
      - PACKAGE_KEY="function.zip"
      - echo "Uploading bundle to s3://${S3_BUCKET}/${PACKAGE_KEY}"
      - aws s3 cp function.zip "s3://${S3_BUCKET}/${PACKAGE_KEY}"
      - echo "Updating Lambda function code from S3 artifact"
      - aws lambda update-function-code --function-name "${LAMBDA_FUNCTION_NAME}" --s3-bucket "${S3_BUCKET}" --s3-key "${PACKAGE_KEY}"

artifacts:
  files:
    - function.zip
    - appspec.yml
    - dist/**/*

cache:
  paths:
    - node_modules/**/*
