version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - echo "Zipping source code..."
      - zip -r function.zip node_modules lambda.js src package.json package-lock.json appspec.yml
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp function.zip s3://event-link-lamba/function.zip
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name event-link --s3-bucket event-link-lamba --s3-key function.zip

artifacts:
  files:
    - function.zip
    - appspec.yml
